# Generated by Django 6.0.1 on 2026-01-15 10:40

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mask_type', models.CharField(choices=[('face', 'Face'), ('hand', 'Hand')], max_length=10)),
                ('image', models.ImageField(upload_to='masks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
