# Generated by Django 6.0.1 on 2026-01-15 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('2D_IMAGE', '2D Image'), ('3D_MODEL', '3D Model')], default='2D_IMAGE', max_length=20)),
                ('file', models.FileField(upload_to='assets/')),
                ('anchor', models.CharField(choices=[('FACE', 'Face Center'), ('HAND_WRIST', 'Hand Wrist'), ('HAND_PALM', 'Hand Palm'), ('HAND_INDEX_TIP', 'Index Finger Tip')], default='FACE', max_length=20)),
                ('scale', models.FloatField(default=1.0)),
                ('position_offset', models.JSONField(default=dict)),
                ('rotation_offset', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomMask',
        ),
    ]
